//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LM_DMS2._0_UI_Automation.LMDMSPortal.LMResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LM_DMS2._0_UI_Automation.LMDMSPortal.LMResources.LMConfig", typeof(LMConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMSPortal.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro Mation.
        /// </summary>
        internal static string DEFAULT_NICE_USERNAME_EU {
            get {
                return ResourceManager.GetString("DEFAULT_NICE_USERNAME_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otto Mation.
        /// </summary>
        internal static string DEFAULT_NICE_USERNAME_NA {
            get {
                return ResourceManager.GetString("DEFAULT_NICE_USERNAME_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string DEFAULT_PASS_EU {
            get {
                return ResourceManager.GetString("DEFAULT_PASS_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string DEFAULT_PASS_NA {
            get {
                return ResourceManager.GetString("DEFAULT_PASS_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eumation.
        /// </summary>
        internal static string DEFAULT_USER_EU {
            get {
                return ResourceManager.GetString("DEFAULT_USER_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to omutation.
        /// </summary>
        internal static string DEFAULT_USER_NA {
            get {
                return ResourceManager.GetString("DEFAULT_USER_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foqawebprd01.xpo.pvt.
        /// </summary>
        internal static string EXTENT_SERVER {
            get {
                return ResourceManager.GetString("EXTENT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Optimizer - Europe -.
        /// </summary>
        internal static string PROJECT_NAME_EU {
            get {
                return ResourceManager.GetString("PROJECT_NAME_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Optimizer -.
        /// </summary>
        internal static string PROJECT_NAME_NA {
            get {
                return ResourceManager.GetString("PROJECT_NAME_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xeadev.xpo.com/MP-Carrier-Portal.
        /// </summary>
        internal static string SERVER_ADDRESS_DEV {
            get {
                return ResourceManager.GetString("SERVER_ADDRESS_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xpodevapp1.xpologistics.com/Xpo.FreightOptimizer.Web.Main.
        /// </summary>
        internal static string SERVER_ADDRESS_MAIN {
            get {
                return ResourceManager.GetString("SERVER_ADDRESS_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://int-desktop.xpolastmile.com/portal.
        /// </summary>
        internal static string SERVER_ADDRESS_QA {
            get {
                return ResourceManager.GetString("SERVER_ADDRESS_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://uat.xpologistics.com/Xpo.FreightOptimizer.Uat.
        /// </summary>
        internal static string SERVER_ADDRESS_UAT {
            get {
                return ResourceManager.GetString("SERVER_ADDRESS_UAT", resourceCulture);
            }
        }
    }
}
